KGU-SSF/SSF-AI

- 조항준/1주차/week1.py
> Week 1 : 조항준 과제 제출

- 최재원/1주차/test.py
> Week 1 :  최재원 과제제출

- 김부연/1주차/weel _1 task.py
> week 1 : 김부연 과제제출

- 이재준/1주차/1주차.py
> Week 1 : 이재준 과제제출

- 김찬영/1주차/test.py
> Week 1 : 김찬영 과제 제출

- 박건우/1주차/hellow.py
> Week1 : 박건우 과제제출

- 송주영/1주차/firstweek.py
> Week 1 : 송주영 과제제출

- 정다연/1주차/test1.py
> Week 1 : 정다연 과제 제출

- 민성준/1주차/GithubTest.py
> Week 1 : 민성준 과제 제출

- 김나윤/3주차/week 3 code.py
> Week 3 : 김나윤 과제 제출

- 민성준/3주차/3주차-1.py
- 민성준/3주차/3주차-2.py
- 민성준/3주차/3주차-3.py
- 민성준/3주차/3주차-4.py
[Week 3 : 민성준 과제 제출 수정](https://github.com/KGU-SSF/SSF-AI/commit/908469813140deaa5be3b32b133f492d1cca4cb1)
> Week 3 : 민성준 과제 제출 수정 

- 조항준/4주차/week4_1.py
- 조항준/4주차/week4_2.py
- 조항준/4주차/week4_3.py
- 조항준/4주차/week4_4.py
- 조항준/4주차/week4_5.py
> Week 4 : 조항준 과제 제출

- 민성준/4주차/week4_1.py
- 민성준/4주차/week4_2.py
- 민성준/4주차/week4_3.py
- 민성준/4주차/week4_4.py
- 민성준/4주차/week4_5.py
> week4 민성준 과제 제출

- 이윤지/4주차/Week4_1.py
- 이윤지/4주차/Week4_2.py
- 이윤지/4주차/Week4_3.py
- 이윤지/4주차/Week4_4.py
- 이윤지/4주차/Week4_5.py
> Week 4 : 이윤지 과제 제출

- 김찬영/4주차/week4-1.py
- 김찬영/4주차/week4-2.py
- 김찬영/4주차/week4-3.py
- 김찬영/4주차/week4-4.py
- 김찬영/4주차/week4-5.py
> Week 4 : 김찬영 과제 제출

- 이다현/1주차/1-1.py
안녕하세요.. vscode연동실패해서 파이참으로 했습니다. tmi지만 제 컴퓨터에 파이썬 경로가 언젠가부터 꼬여서 vscode로 파이썬을 못씁니다. 감사합니다..
> Week 1 : 이다현 과제 제출

- 조항준/5주차/5-1.py
- 조항준/5주차/5-2.py
- 조항준/5주차/5-3.py
안녕하세요 5주차과제 제출합니다.
코드리뷰
1번
인원수를 n에 저장하고 n만큼 반복하여 점수를 scores라는 리스트에 입력받습니다. 이후 평균을 출력합니다.
2번
줄 개수를 n에 입력받고 n-i만큼 반복하여 공백을 추가합니다 이후 i만큼 별을 출력합니다.
예시 : 4개의 경우 첫째줄에는 공백 3개 별1개 두번째줄은 공백2개 별2개 세번째 줄은 공백1개 별3개 네번째 줄은 공백 0 개 별 4개
3번
먼저 윷의 경우를 체크하는 코드는 함수로 구현하여 편하게 호출할수 있도록 구현였습니다. 따라서 리스트의 count를 이용하여 0과 1의 개수를 확인하고 check함수에 매개변수로 전달하여 함수를 실행합니다.
> Week 5 : 조항준 과제 제출

- 이현준/5주차/5-1.py
- 이현준/5주차/5-2.py
- 이현준/5주차/5-3.py
1. 이 코드는 5명의 성적을 입력받은 후 성적의 평균을 구하는 프로그램이다. n에 5를 저장한 후 n만큼 반복되는 for문을 만들고 입력된 각 grade가 범위를 벗어났을 때 프로그램이 종료되며, 성적이 50보다 낮다면 성적을 50으로 조정힌다. grade가 범위 내에 있다면 sum 변수에 성적을 계속해서 더한 후 마지막에 sum을 n으로 나누어 평균을 구한 후 출력한다.
2. 이 코드는 사용자로부터 높이를 입력 받은 후 피라미드를 출력하는 프로그램 이다. 사용자에게 N을 입력 받은 후 for문을 활용하여 입력 받은 높이만큼 피라미드가 출력된다. 맨 윗층 이후의 문자끼리는 한칸 씩 띄어놓기 위해 이중 for문으로 구현하였다.
3. 이 코드는 사용자로부터 윷의 상태를 입력 받아 윷놀이 결과를 출력하는 프로그램이다. for문을 활용하여 윷의 상태를 리스트로 3번 입력받고 리스트 속 요소나 리스트의 길이가 범위를 벗어난 경우에는 프로그램을 종료한다.  그 이후 for문을 활용하여 입력된 요소를 sum 변수에 각각 더하고 더한 결과에 맞는 윷놀이 결과를 출력한다.
> Week 5 : 이현준 과제 제출

- 고석훈/5주차/5-1.py
- 고석훈/5주차/5-2.py
- 고석훈/5주차/5-3.py
1. 1번 문제는 5명의 학생들의 점수의 평균을 구하는 코드이다. 5명의 학생들의 성적을 입력 받기 위해 반복문을 사용하여 5번의 반복을 한다. 성적이 50 미만인 경우 해당 성적을 50으로 조정한다. 학생들의 성적을 모두 더해 5로 나누어 평균 성적을 구한다.  
2. 2번 문제는 피라미드의 높이를 입력 받고 피라미드를 출력하는 코드이다. 사용자에게 N값을 받아  반복문을 사용해 N값 만큼 피라미드의 높이가 출력 되게 하였다.  공백의 개수는 피라미드의 높이에서 현재 층의 번호를 빼어 각층마다 공백을 출력한다. 현재 줄에 출력할 별의 개수를 결정하기 위해 range함수를 사용하여 현재 줄의 높이 만큼 반복하게 했다.
3. 3번 문제는 윷놀이 결과를 분석하여 도, 개, 걸, 윷, 모를 판별하고 이에 따라 결과를 출력하는 코드이다. for문을 이용하여 3번의 입력을 받고 조건문을 통해 각 입력에서 back(1)의 개수마다 윷놀이의 결과를 출력하게 하였다.
> Week 5 : 고석훈 과제 제출

- 정지훈/5주차/5-1.py
- 정지훈/5주차/5-2.py
- 정지훈/5주차/5-3.py
1번 문제:
for 반복문을 이용하여 값을 받을 때 if 문을 사용해 먼저 받은 값이 5의 배수가 아니면 break로 프로그램을 끝냄.
두 번째 if 문에서는 받은 값이 50 미만이면 받은 값을 50으로 변환함. 받은 값들은 sum 변수에 누적해서 더함.
마지막으로 average 변수에 누적된 점수(sum) 을 5로 나누어 평균을 구함.
2번문제:
사용자가 입력한 값을 N에 저장.
for 문 - 공백을 출력하는 값을 " "*(N-i)로 하였음 N은 고정된 값이고 i는 for 문에 의해 점점 커지므로 줄이 바뀔 때마다 공백의 개수가 하나씩 줄어들어 삼각형 모양 연출이 가능
공백 출력 이후에는 별을 출력해야 하는데 별의 개수는 줄바꿈이 있을 때마다 개수가 늘어나 "*" * i 로 하였는데 출력 예시에 별 뒤에는 항상 공백이 있으니 "* " * i 로 출력하였음
3번 문제
첫 번째 줄에 map(int,input().split())을 사용해 공백을 기준으로 정수를 받음 도, 개, 걸, 윷, 모 를 판단하는 기준이 0과 1의 개수이므로 받은 값을 다 더해서 나온 값을 기준으로 if 문을 사용하여 도,개,걸,윷,모를 판단함
> Week 5: 정지훈 과제제출

- 김나연/5주차/week5-1.py
- 김나연/5주차/week5-2.py
- 김나연/5주차/week5-3.py
5-1
for문으로 5개의 정수를 입력 받고, i로 받는 정수가 50미만이면 result 리스트에 50으로 들어가게 하고 나머지를 i로 받은 정수 그대로 result 에 append 함. sum함수와 len함수를 이용해서 평균을 구한 후 int를 씌워서 출력함.
5-2
for문으로 0에서 num-i-1만큼 공백을 찍고, 두 번째 0에서 i+1만큼 *을 찍어 피라미드를 만듦.
5-3
for 문 이용하고 input을 통해 들어오는 문자를 띄어쓰기 단위로 잘라서 int 자료형으로 변환 후 list 형태로 저장함. list형 변수인 a에서 정수 0의 개수를 카운트하여 1개면 ‘A’,  2개면 ‘B’, 3개면 ‘C’, 4개면 ‘D’, 그 외에 경우 ‘E’를 출력함.
> Week 5 : 김나연 과제 제출

- 권우진/5주차/5-1.py
- 권우진/5주차/5-2.py
- 권우진/5주차/5-3.py
1번.
인원이 5명이라 for문을 5번 돌려서 li_score에 5명의 점수를 append하고 하나씩 꺼내서 50점 미만은 50점으로 고정하고 평균을 구함
2번.
2중 for문에서 첫 번째는 0에서 n - i - 1만큼 공백을 찍어 내는 것이고 두 번째는 0에서 i + 1만큼 별을 찍고 공백을 찍음
3번.
입력 값을 딕셔너리에 1차원 리스트를 value로 하여 세 개를 넣었고 리스트에서 값을 하나씩 꺼내어 1과 0을 비교하여 도, 개, 걸, 윷, 모를 특정함
> Week 5 : 권우진 과제 제출

- 문준호/5주차/5-1.py
- 문준호/5주차/5-2.py
- 문준호/5주차/5-3.py
**1. 점수 입력받고 평균 구하기**
학생들의 점수를 저장해놓는 것이 필요하다고 생각하여 student라는 list에 5번 점수를 append할 수 있도록, for문을 구현했습니다. 이때, 50점 이하면 50점이 담기도록 조건문을 달았습니다.
그리고 각 리스트를 순회하며 sum에 총 합을 구하고,
이를 5로 쪼개서, 평균을 구했습니다.
5회로 문제에 지정되어 있어서 문제는 없지만, len(student)를 쓰는 것이 나았을 것 같다는 아쉬움이 있습니다.
소수점 둘째자리까지만 나오도록 format했습니다.
_**++5의 배수로만 입력받는 것을 간과하고 코딩했습니다.
죄송합니다.**_
**2. 별 그리기**
2중 for문을 이용하여 구현했습니다.
첫번째 for문에서 ((입력받은 횟수)- i)만큼 공백을 입력받아 가운데에서 별이 위치하도록 만들었습니다.
두번째 for문에서는 "*"이 입력되고, 그 뒤에 공백을 위치 시켜 간격을 유지시켰습니다.
그 결과 왼쪽 상단에 빗변이 우측을 보고 있는, 공백으로 구성된 직각삼각형과, 그 직각삼각형 옆에 바로 위치된, *로 이루어진 이등변 삼각형 형태를 구성하였습니다.
**3. 윷놀이**
spilt과 map(int), list()를 이용하여, 4개를 쪼개어 int자료형이 든 list로 입력받았습니다.
이를 list1에 append 시켜, 2차원 list를 만들었습니다.
2중 for문과 조건문을 이용하여, 행의 값들을 전부 더해서, 이를 이용해서 도 개 걸 윷 모를 구분하도록 코드를 짰습니다.
> Week 5: 문준호 과제 제출

- 민세라/5주차/5-1.py
- 민세라/5주차/5-2.py
- 민세라/5주차/5-3.py
[5-1]
점수를 저장할 빈 리스트(li)를 만든 후 for문으로 5명의 점수를 받아오는 과정에서
if문으로 50점 미만인 학생의 점수는 점수를 50점으로 바꾼 후 리스트에 저장한다.
result라는 변수 선언 후 for문을 사용하여 result에 리스트의 값을 하나하나 더한다.
그 후 출력할 때 //5를 하여 평균 값 출력(/5를 하면 소수점까지 출력되어 몫만 구하는 //를 사용함)
[5-2]
별과 빈칸의 규칙성을 찾아보면 빈칸(' ')이 첫번째 줄에는 입력된 값의 -1을 한 값부터 한 줄마다 1씩 줄어들고
별+빈칸('* ')은 첫째 줄 부터 한개 씩 입력된 값까지 1씩 증가중인 것을 알 수가 있다.
그러므로 값을 입력 받고 변수b(빈칸 개수)에 그 값보다 1 작은 값을 저장 후 for문을 사용하여 입력 받은 값 만큼
반복 하고 end를 사용하여 줄바꿈이 되지 않게 하면서 중첩 for문을 사용하여 '* '을 i만큼 반복하여 출력하게함
(이부분도 줄바꿈을 하면 안돼서 end=''사용)
빈칸 개수는 줄마다 한개씩 줄어야 하므로 b-=1을 작성, 그 후 print('')를 사용해서 줄바꿈 해주기
[5-3]
입력 값을 받아올 때 빈칸을 기준으로 하여 리스트에 저장 하고 1이 몇개 있는지 확인하기 위해 cnt변수 선언,
그 후 for문을 사용하여 리스트에 저장된 1의 개수를 확인한다.
if문을 사용하여 만약 1의 개수가 1개라면 A, 2개라면 B, 3개면 C, 4개면 D, 나머지는 E로 출력한다.
> Week 5 : 민세라 과제 제출

- 이진서/5주차/5-1.py
- 이진서/5주차/5-2.py
- 이진서/5주차/5-3.py
<5-1>
각자의 이름을 딴 변수를 만들어 정수형으로 입력 받는다. if문을 이용해 입력받는 각 변수가 50 미만일 경우 변수의 값이 50이 되도록 한다.
최종적으로 결정된 변수들의 값의 평균을 내어 출력한다.
<5-2>
하나의 변수(lL)를 정수형으로 입력받는다. if문을 사용해 만약 입력 받은 변수가 0 미만 또는 100 초과일 경우 Error를 출력하고 작동을 중지하게 만든다. for 문을 이용해 i 라는 변수를 1부터 L까지 반복하게 만든다.  print를 이용해 공백이 (L - i)개 만큼 출력되게 하고, end = ''를 이용해 공백이 옆으로 출력되도록 한다. 또한 for문을 이용하여 별을 i개 만큼 출력되게 한다. 별을 출력 후 print()를 통해 줄바꿈을 하도록 한다.
<5-3>
a1이라는 함수를 4개의 값을 입력했을 때 값들의 합을 담도록 정의한다. 또한 i1이라는 변수를 입력받는다. i1 를 정수형으로 입력받아 n1이라는 리스트 안에 담기게 한다. 또한 split()를 이용해 공백으로 값들을 구분하도록 한다. 그리고 r1이라는 변수 안에 a1의 결과가 담기도록 한다.
총 3줄을 입력받아야 하기 때문에 변수의 이름을 조금씩 변경하여 위 과정을 3번 반복한다.
후에 If문을 이용해서 입력받은 값 들의 합에 따라 알파벳이 나뉘도록 한다.
> Week 5: 이진서 과제 제출

- 장소원/5주차/5-1.py
- 장소원/5주차/5-2.py
- 장소원/5주차/5-3.py
5-1
input을 통해 사용자에게 점수를 받고 if문을 사용해 그 점수가 50점보다 낮으면 사용자에게 받은 점수를 50점으로 변경하고 50점보다 같거나 높으면 그대로 둔다 이 과정을 5번 반복한 뒤 print로 평균을 구한다
5-2
input을 통헤 사용자에게 숫자 n를 받고 for을 사용해 변수 i를 n 만큼 늘린다 그러고 공백과 *의 위치를 파악하면 공백은 n-i만큼 * 은 i번 만큼 for을 통해 반복하면 피라미드 형의 모양이 나온다
5-3
input().split()을 통해 4개의 숫자를 한번에 받는다 근데 .split()을 해서 받으면 리스트에 문자형으로 받아지기 때문에 숫자들을 밑의 a=int(a)로 문자를 int형으로 바꿔준다 그런 다음 if문을 사용해 숫자들의 합으로 도개걸윷모를 구분한다
Q. 5-3문제를 다른 방법으로 푸는 방법을 알고싶습니다
> week 5 : 장소원 과제 제출

- 김동현/5주차/5-1.py
- 김동현/5주차/5-2.py
- 김동현/5주차/5-3.py
김동현 과제제출 드립니다.
첫 번째 코드 : 
input을 int 형으로 받아들이는 방법을 복습하였습니다.
나머지('%') 연산자와 같다(==), 아니다(!=) 연산자에 대해서 복습하였습니다.
오류가 나는 것을 방지하고자 조건에 명시된 정수가 아닐 경우 재입력하도록 while문에 조건을 걸어서 다시 input 요청하도록 했습니다.
두 번째 코드 : 
두 변수들을 입력하도록 하여, a는 ' *'을 출력하는데에 사용, b는 ' '를 출력하는데에 사용했습니다.
for 문을 이용, 입력된 정수까지의 줄 만큼 반복되도록 range의 입력값을 a+1로 수정했습니다.
b 변수를 이용해서 공백을 입력하는 과정에서 맨 마지막 줄의 경우 공백의 개수가 0이므로 for문 실행 전 b의 입력값에 1을 더했습니다.
세 번째 코드 : 
list(map(int,input().split())) 코드를 사용하여 네 숫자를 공백 기준으로 각각 인식하도록 했습니다. split() 함수는 공백을 기준으로 요소를 나누는 역할을 합니다. map() 함수는 input.split으로 입력된 요소들을 int 형식으로 인식하도록 하는 역할을 합니다. 추후 map함수와 list 에 대해서 추가로 공부할 예정입니다. 이후 입력받은 숫자들을 더해서 0, 1, 2, 3, 4별로 다른 경우의 수가 나오도록 했습니다.
p.s. 코드 리뷰하는 과정에서 내용 복습이 되어 좋은 것 같습니다. 감사합니다.
> Week 5 :  김동현 과제 제출

- 최민규/5주차/5-1.py
- 최민규/5주차/5-2.py
- 최민규/5주차/5-3.py
5-1 : 
배열 a 크기 5로 생성
각 성능 입력 받고 50안넘을 시 50으로 정정
sum총합 구해서 5로 나눈 값을 정수로 출력
5-2 :
정수 a입력받고 a만큼 반복
각 i번째 줄에서 a-i만큼 공백, i만큼  *출력
매 줄이 끝나면 줄바꿈
5-3 :
한 줄로 입력 받아 리스트 생성
리스트에서 0의 개수 카운트
결과값 딕셔너리 0의 개수만큼 알파벳 할당 
카운트로 결과 출력
> Week 5 : 최민규 과제 제출

- 김승재/5주차/5-1.py
- 김승재/5주차/5-2.py
- 김승재/5주차/5-3.py
문제 1 : 성능 점수를 줄마다 입력받기 위해 for문을 통해서 값을 입력받고 해당 값이 0보다 작거나 100보다 클 경우, 그리고 입력된 값이 5의 배수가 아닐 경우 break문을 통해  반복문을 빠져나감. 그리고 해당 점수가 50점 미만일 경우 보충 수업을 들어 점수가 50점으로 되므로 조건문을 통해 입력된 값이 50점보다 작을 경우 해당 값을 50으로 변경해줌. 입력된 값을 sum 변수에 더해 저장한 후 average 변수에 평균을 구한 값을 저장함. 5명의 입력을 받아으므로 평균을 구하기 위해 5로 나누고 해당 값이 정수로 출력되어야하기 때문에 int(sum / 5)으로 계산 후 average 변수에 출력
문제2  : 예시로 출력된 화면을 보면 일정한 규칙을 발견 할 수 있는데 입력한 값을 x, 해당 번째 줄은 i번째 줄이라 할 때 모든 줄은 처음으로 별이 출력되기 전에 (x-i)번의 공백이 있고 별이 출력되고 있고, 별은 공백과 같이 i번 반복되므로 " "*(x-i)를 통해 공백을 먼저 출력해준 후  "* "*i를 통해 별을 반복해서 출력해줌
문제 3: 입력된 줄의 결과를 저장해주기 위해 sum이라는 리스트를 생성. 0 또는 1이라는 값을 한 줄에 네번 입력받아야 하므로  a,b,c,d = map(int,input().split())를 통해 네 값을 동시에 저장함 그리고 도,개,걸 윷,모를 판별하기 위해 if-elif문을 사용하여 각 값마다 경우를 나누어 A,B,C,D,E를 설정. 그리고 마지막에 반복문을 통해 결과가 저장되어있던 sum 리스트 값들을 출력해줌
> Week 5 : 김승재 과제 제출

- 김수민/5주차/5-1.py
- 김수민/5주차/5-2.py
- 김수민/5주차/5-3.py
1번 문제 - 정수형으로 변수를 받은 후 50이하이면 50으로 바꾸어주고 평균을 구한다
2번 문제 - 원하는 별의 수를 정수형으로 입력받고 print(" "*(a-i), end="")으로 첫번째 *시작 전 공백, print("*", end=" ")으로 별 출력 후 줄바꿈이 되지않고 별과 공백 번갈아가며 출력, print("*")으로 마지막 별 출력 후에는 공백X - 2번 문제는 구글링하며 해결했습니다..
3번 문제 - 각 윷의 상태를 .split으로 띄어쓰기 기준으로 각 변수로 지정해 주고 int를 통해 정수형으로 변환 후 윷 상태를 파악하고 결과 출력하는 함수 선언 후 출력.
> Week 5 : 김수민 과제 제출

- 장현진/5주차/5-1.py
- 장현진/5주차/5-2.py
- 장현진/5주차/5-3.py
5-1. 성능을 사용자에게 5번 받아서 grade리스트에 넣는다. 사용자에게 받은 성능이 50미만이면 50,성능이 50이상이면 그대로 result리스트에 넣는다. 그리고 난후 sum함수랑 len함수를 사용해서 평균을 구한뒤에 print한다.
5-2.숫자를 사용자에게 입력받아 a에 할당한다. for반복문을 이용해서 1에서 a까지 반복하여 공백을 a-i만큼 곱한 뒤 print한다.(공백은 a에서 하나씩 줄어들고 별은 하나씩 늘어나 피라미드 구조를 형성함)
5-3.사용자에게 입력받은것을 공백을 기준으로 나누어서 리스트에 넣는다. 그런 후 문자형인 요소들을 int(_)의 _자리에 넣어 정수형으로 바꿔준 후 sum에다 더한다. if문을 사용하여 sum을 기준으로 조건문에 맞게 print 한다
> Week 5 : 장현진 과제 제출

- 김신/5주차/5-1.py
- 김신/5주차/5-2.py
- 김신/5주차/5-3.py
5-1 : 성능 값을 반복문을 통해 5번 입력 받아 결과 리스트에 넣는데, 50 미만일 경우 50으로 변환해 넣고 아닐 경우는 그대로 넣는다. 그렇게 만들어진 결과 리스트를 리스트 요소 개수만큼 나누어 평균을 구한다.
5-2 : 1부터 100 사이의 수 n을 입력 받는다. center 함수를 쓰면 가운데 정렬이 되는데 n의 최댓값이 100이므로 전체 칸 수를 100으로 하고 *이 아닌 부분은 공백이어야 하므로 빈칸을 따옴표 안에 넣었다. 따라서  *가 1부터 n개가 될 때까지 반복 총 n번 가운데에 출력된다.
5-3 : map함수를 통해 입력 받은 값을 정수형으로 변환하고 리스트에 넣는다. count를 통해 입력 받은 0의 개수를 세고 0의 개수에 따라 다른 문자가 출력되도록 result를 만들어 출력했다.
> Week 5 : 김신 과제 제출

- 이유림/5주차/5-1.py
- 이유림/5주차/5-2.py
- 이유림/5주차/5-3.py
5-1
5명의 점수를 입력하기 위해서 int와 input을 써서 점수를 받고 if문을 사용해서 각각의 점수가 50점 이하인 경우에는 50으로 바꿔준다. 그리고 나서 5명의 평균값을 구하기 위해서 50명의 점수를 다 더하고 5로 나눈 값을 출력한다.
5-2
N으로 몇 번째 줄까지 피라미드를 만들지 입력하고 for문을 사용해서 먼저 n번째 줄에는 n-1만큼의 빈칸이 나오므로 빈칸이 먼저 출력되고 그 다음에 n번째 줄만큼 별 n개가 출력되기 때문에 n개의 별이 나오게한다. 이때, 별 한 개가 출력되면 한 칸 뛰고 다음 별이 출력되므로 별 한 개와 빈칸 하나가 같이 출력되게 한다.
5-3
먼저 윷짝의 상태를 각각 첫째 줄부터 셋째 줄까지 입력하게 하는데 빈칸을 두고 입력해야하기 때문에 split를 사용하고 그 다음에 각 줄마다 if문을 사용해서 배와 등의 개수에 따라 결과가 A, B, C, D, E가 출력되게 한다.
> week 5 : 이유림 과제 제출

- 최재원/5주차/5-1.py
- 최재원/5주차/5-2.py
- 최재원/5주차/5-3.py
1. 반복문으로 성적을 각각 입력받고 50점 이하면 점수를 50으로 아니면 점수를 그대로 유지! 그후 평균 구하고 출력 시키기
2.. 별 갯수를 받은후 우선 빈칸을 만들어야 하니 star - i 로 앞 빈칸을 만든후 *은 i만큼 출력
3.  윷을 입력 받고 도개걸윷모는 합을 이용해서 구할수 있으므로 모두 더해 1이면 도, 2면 개 등등 으로 구한다
> Week 5 : 최재원 과제제출

- 박관호/5주차/5-1.py
- 박관호/5주차/5-2.py
- 박관호/5주차/5-3.py
#코드 리뷰
1번 문제는 리스트와 for문과 if문을 쓰면 충분히 해결할 문제라 생각하고 접근하니 풀렸다. 일단 가장 먼저 입력 받는 값이 줄 단위로 여러 개 이기 때문에 이거는 리스트에다 값이 저장되게 .append 메소드를 사용했다. (여러 개로 저장되야 되니까 for in range로 갯수 지정). 그 담에 50점 미만은 항상 50점이라 했으니 if문 걸어주고..  그 담에 리스트에 저장된 값을 평균을 구하도록 만들어 놨다.(for 문 range 돌면서 각 값 합치면서 리스트 길이 나누기)
2번 문제는 일단은 for문을 3번 돌려야하는데 첫번째로 도는거는 줄 바꿈, 2번째로 도는거는 공백 출력하기, 3번째로 도는건 애스터리스크 출력하기. 라고 접근한다. 그리고 수열 문제기 때문에 input한 n에 따라 수열이 나타나져야 하므로 n을 num으로 변수 지정. 아마도 이 num으로 for 문의 루프에 적절히 넣어져야 할 것으로 생각했다. 이 문제의 규칙은 첫번째줄은 별이 나타나기 전까지 공백이 num-1이고 두번째 줄은 num-2, 세번째 줄은 num-3이기 때문에 첫번째 for문은 당연히 range(0, num). 두번 째 for문은 range(i+1, num). 그리고 첫 번째 줄은 별이 1개, 두번째 줄은 별이 두개, 세번째 줄은 별이 세 개 이므로, 세 번째 for문은 range(0, i+1).(여기서 도는 범위를 i+1로 설정한 이유는 줄 바꾸는 수랑 애스터리스크 나타나는 수랑 같게 하기 위해서다.) 근데 주의할 점은 별표 사이에 한칸씩의 공백이 있기 때문에 "* " 로 출력해야한다.
3번 문제는 …
> week 5 : 박관호 과제 제출

- 이채은/4주차/4-1.py
- 이채은/5주차/5-1.py
- 이채은/5주차/5-2.py
- 이채은/5주차/5-3.py
5-1
num_scores = int(input("몇 개의 성능 입력하시겠습니까? ")) 
ㄴ 사용자로부터 몇 개의 성능을 입력 받을 것인지 묻는다.
scores = []
ㄴ 성능을 저장할 빈 리스트를 생성하는 데 사용된다.
for i in range(num_scores):
ㄴ 0부터 '사용자가 입력한 수(num_scores) - 1'까지의 범위를 반복하게 하기 위한 코드이다.
score = input(f"{i+1}번째 성능을 입력하세요: ")
score = 50 if int(score) < 50 else int(score)
scores.append(score)
ㄴ 사용자로부터 각각의 성능을 입력 받고, 입력된 성능이 50보다 작으면 성능을 50으로 설정되도록 한다.  50보다 크거나 같으면 입력된 값을 그대로 정수로 변환되도록 한다. 그리고 이렇게 입력된 성능을 scores 리스트에 추가하도록 한다.
average = sum(scores) / len(scores)
print(f"입력하신 성능들의 평균은 {average:f}입니다.")
ㄴ 리스트의 합을 계산하고, 성능의 개수로 나누어 평균을 계산한다.
5-2
n = int(input("숫자를 입력하세요:"))
ㄴ 사용자로부터 숫자를 입력 받는다.
for i in range(1, n+1):
ㄴ 1부터 n까지의 범위를 반복한다. (그리고 이 코드는 삼각형의 높이를 결정한다.)
for j in range(n-i):
ㄴ 삼각형의 왼쪽 부분에 공백을 넣어주기 위한 코드이다.
print(" ", end="")
ㄴ 공백을 출력하는 코드이다.
for j in …
> Week 5 : 이채은 과제 제출

- 김예은/5주차/5-1.py
- 김예은/5주차/5-2.py
- 김예은/5주차/5-3.py
1.각각의 점수를 for문으로 5번 받게 한 후 합계를 구한 후, 합계를 5로 나눈 후 평균값을 구함
2.별 몇 개를 출력할 건지 input으로 받은 뒤, for문을 사용하여 1부터 N=1까지 범위를 잡은 뒤, 공백*(N-1) 더하기 i별공백을 해서 피라미드 모양의 별을 출력함.
3.split을 사용하여 input받은 숫자를 공백마다 나누고 map을 사용하여 a,b,c,d에 각각의 숫자를 대입하게 만듦. if문으로 각 자릿수의 합이 각각의 윷놀이 숫자에 해당하게 하여 ABCDE를 출력함.
> week 5 : 김예은 과제 제출

- 최인규/5주차/week5-1.py
- 최인규/5주차/week5-2.py
- 최인규/5주차/week5-3.py
> Week 5 : 최인규 과제 제출

- 김진영/5주차/5-1.py
- 김진영/5주차/5-2.py
- 김진영/5주차/5-3.py
5-1 :
a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
: a b c d e 변수를 입력한다
if a <50 :
a=50
if b<50 :
b=50
if c <50 :
c=50
if d <50 :
d=50
if e <50 :
e=50   
: if문을 사용하여 입력 받은 값 a b c d e의 조건을 통해 값을 매긴다
print((a+b+c+d+e)//5)
: print를 사용하여 a b c d e의 평균값을 출력하고, //를 이용하여 평균값을 구한다
5-2 :  
a=int(input("변수를 입력하시오 : "))
: 변수를 입력 받는다
for i in range(1,a+1) :
print(" "*(a-i) +"* "*i)
: for문을 사용하여 1부터 a까지 숫자 범위를 반복한다
" "*(a-i)은 공백 문자를 출력
i의 값에 따라 *의 개수가 결정
5-3 : 
for e in range(3) : 0부터 2까지 범위에서 반복문을 실행한다
sum = 0 : 반복마다 합산한 수를 저장할 변수 sum을 0으로 초기화한다
s = input().split() : 입력을 받아 문자열을 분리해서 리스트 s에 저장한다
for_in s : 리스트 s의 각 내용 반복문을 시작
sum += int(_) : 리스트의 요소를 정수형으로 바꿔 sum에 더한다
if(sum==3)  , elif(sum==2), elif(sum==1) , elif(sum==0) , else : 결과에 따라 문자를 출력하기 위해서 그에 맞는 조건문을 사용
> week5 : 김진영 과제 제출

- 조항준/6주차/6-1.py
- 조항준/6주차/6-2.py
- 조항준/6주차/6-3.py
안녕하세요. 6주차 과제 제출합니다.
6-1 의 경우 : 문자열의 중간점을 기준으로 왼쪽과 오른쪽을 끝에서부터 각각 비교하도록 구현하였습니다
6-2 의 경우 : 0인 경우 pop을 이용하여 리스트의 요소를 꺼내도록 하였고, 아닌경우 append 를 통해 리스트에 요소를 추가하도록 하였습니다.
6-3 의 경우 : 먼저 요소를 append를 통해 추가하였고, sort를 이용하여 정렬한 리스트를 출력하도록 하였습니다.
해결되지 않는 문제, 오류 X
과제에 대해 궁금한 점 X
추가적인 궁금점 X
> Week 6 : 조항준 과제 제출

- 장소원/6주차/6-1.py
- 장소원/6주차/6-2.py
- 장소원/6주차/6-3.py
6-1
input으로 회문인지 아닌지 판단할 문자를 a로 입력받는다 
회문이면 True 회문이 아니면 False를 출력할 함수를 b라고 하고 기본 값을 True라고 잡는다  
for문을 사용해 문자 a의 총길이의 반만큼 i가 반복하게 한다
if문을 사용해 문자 a의 처음부터 시작해 올라가는 것(=a[i])과 뒤에서 시작해 내려가는 것(=이 경우 i가 0부터 시작하기 떄문에 a[-i]가 아닌a[-1-i])을 비교하며 다를경우 b에 Flase를 넣고
더이상 볼 필요가 없으므로 break로 빠져나오게 한다 
print(b)를 해 회문이 맞다면 True가 아니라면 Flase가 나오게 한다
6-2
"from collections import deque"을 사용해 큐 자료구조 구현을 위해 deque 라이브러리를 사용할 수 있게 한다
input을 사용해 a에 총 입력할 수의 갯수를 받는다
b라는 deque 라이브러리를 만든다
sum이라는 변수를 0이라고 만들어 놓는다
for을 사용해 a번 반복해서 c에 변수를 받는다
if를 사용해 c가 0 이면 pop()을 사용해 b에 있는 가장 최근의 수를 지우고 0이 아니면 b에 수를 추가한다
그렇게 추가되고 지운 후 최종의 b의 길이를 d라고 받는다
for을 사용해 d만큼 반복하는데 제거하는 b의 수를 e라고 받고 sum에 e를 계속해서 추가하여 합을 받는다
받은 sum을 print한다
6-3
사용자에게 총 입력할 수의 갯수를 a로 입력받는다
사용자에게 입력받은 수들을 넣을 b라는 리스트를 만든다
for문을 사용하여 i를 a번 반복하게 한 후 c로 수를 입력받아 .append()를 …
> week 6 : 장소원 과제 제출

- 이찬혁/6주차/6-1.py
- 이찬혁/6주차/6-2.py
- 이찬혁/6주차/6-3.py
6-1. hoimoon(회문) 함수 만들고,
strin은 입력될 문자열, strlength는 반복분에 쓰기 위해 (문자열 길이 - 1)해주고 문자열 길이가 짝수면 반 갈라서 확인하고 홀수면 가운데 빼고 확인하기 떄문에 int형변환으로 (strlength/2)의 소수점 버렸습니다. 그리고 양 쪽을 확인해서 같지 않은게 발견되면 false를 반환
전부 통과하면 true를 반환합니다.
6-2. loop는 입력받을 숫자의 갯수,
numlist는 처음에 비어있는 배열로 하고 0이면 numlist의 마지막 항목을 지우는데 만약 numlist에 들어있는 게 없다면 지울 수 없기 때문에 if와 len()으로 검사하고 실행합니다. 입력이 끝나면 sum()으로 모든 항목을 더하여 print합니다.
6-3. numOfint는 받을 숫자의 개수이고 numList라는 빈 배열을 준비합니다. append(int(input()))으로 numList에 수들을 넣고, sort()로 정렬하고 반복문으로 정렬된 각 항목의 값을 출력합니다.
> Week 6: 이찬혁 과제 제출

- 권우진/6주차/6-1.py
- 권우진/6주차/6-2.py
- 권우진/6주차/6-3.py
1번
덱에 문자를 하나씩 넣어주고 reverse 함수로 덱을 반전 시켜서 두개의 덱을 비교함
2번
숫자를 입력받아 그 숫자가 0일경우 덱에서 pop 함수로 빼주고 아닐땐 append 함
3번
덱에 값을 받아주고 선택정렬 알고리즘으로 remove 함수로 덱에서 해당 값을 삭제, appendleft 함수로 덱의 왼쪽에서 가장 큰값부터 하나씩 넣음
궁금한 점 :  덱과 리스트가 거의 똑같다고 느낌. 덱이 리스트보다 입출력이 효율적인 장점 말고 다른게 있는지 또 왜 덱을 사용하는지 궁금함
> Week 6 : 권우진 과제 제출

- 이현준/6주차/6-1.py
- 이현준/6주차/6-2.py
- 이현준/6주차/6-3.py
1) 사용자로부터 단어를 입력 받은 후 단어가 회문인지 판단하는 프로그램이다. 사용자로부터 word를 입력받은 후 for문을 사용하여 입력받은 단어를 하나하나 큐에 입력한 후 그 큐와 정렬이 반대되는 큐를 생성한다. 이후 reverse와 queue가 같다면 회문으로 판단하여 True를 출력하고 아니라면 False를 출력한다.
2) 사용자로부터 몇개의 숫자를 입력받을지 사용자로부터 입력받는 후 변수 K에 저장한다. 이후 K개의 숫자를 순차적으로 입력받은 후 numbers라는 리스트에 저장한다. 만약 순차적으로 입력 받은 숫자가 0~9의 범위를 벗어났으면 프로그램을 종료한다. 순차적으로 입력받은 숫자 중 0이 있다면 가장 최근에 적은 숫자를 지운다. 그렇지않다면 숫자를 큐에 삽입한다. 이후 큐 속의 값을 모두 더한 값을 반환하고 이를 출력한다.
3) 사용자로부터 숫자를 입력받은 후 이를 오름차순으로 정렬한 뒤, 이를 출력하는 프로그램이다. 사용자로부터 몇개의 숫자를 입력받을 지 입력받은 후, 이를 N에 저장한다. 이후 숫자를 차례대로 입력받고 이 숫자를 numbers에 리스트로 저장한다. 이후에 sort를 활용하여 리스트 속 요소를 오름차순으로 정렬한 뒤 for문을 활용하여 리스트 속 요소를 하나씩 출력한다.
> Week 6 : 이현준 과제 제출

- 이채은/6주차/6-1.py
- 이채은/6주차/6-2.py
- 이채은/6주차/6-3.py
6-1
for i in range(3):
word = input('단어를 입력하세요: ')
ㄴ 사용자로부터 입력을 받고 값을 word 변수에 저장하는 것을 3번 반복하게 한다.
print(word == word[::-1]) 
ㄴ word == word[::-1]은 입력 받은 단어를 거꾸로 나열한 것과 원래 단어가 동일한지 비교하여 True와 False를 출력할 수 있도록 한다. (word[::-1]은 입력 받은 단어를 거꾸로 만드는 코드이다.) 
6-2
N = int(input())
cards = []
ㄴ 카드의 개수를 입력 받고 카드를 저장할 리스트를 만든다.
for _ in range(N):
card = int(input())
cards.append(card)
ㄴ 카드를 입력 받아서 리스트에 새로 추가하는 과정을 N번 반복한다.
num = []
total_sum = 0
ㄴ 0이 아닌 수를 저장할 리스트를 만들어서 0이 아닌 수들을 이 리스트에 추가한다.
for card in cards:
if card != 0:
num.append(card)
total_sum += card
ㄴ 리스트에 있는 카드 숫자들이 0인지 아닌지 확인하는 과정을 반복한다. 카드 숫자가 0이 아니면 num 리스트에 추가하고 total_sum에 더한다.
else:
if num:
removed_card = num.pop()
total_sum -= removed_card
ㄴ 카드 숫자가 0인 경우, num 리스트에서 가장 최근에 추가된 카드 숫자 제거하고 total_sum에서도 그 수를 뺀다.
print(total_sum)
ㄴ 최종으로 …
> Week 6 : 이채은 과제 제출

- 최재우/6주차/6-1.py
- 최재우/6주차/6-2.py
- 최재우/6주차/6-3.py
1. 회문을 판별하여 회문이면 ture 아니면 ffalse를 출력하는 코드. 
변수 a에 값을 받아, lower로 대소문자가 달라 생기는 오류를 막고, a의 값이 a의 역순과 일치하지 않을 경우 b값을 false로 설정하여 값을 출력. 
2.  내려놓은 1~9 사이의 카드들의 합을 출력하는 코드. 단, 0을 말할 경우 가장 최근 내려놓은 값은 사라진다.
첫번째 줄에 반복할 횟수를 설정하고, b라는 리스트를 생성. 반복문을 통해 a번만큼 c값을 입력하고, c값이 0이라면 가장 최근 추가된 값을 제거하고, 아닐 경우 b에 c값을 추가한다. 이후 b의 값을 전부 더해 출력. 
3. n개의 수가 주어지고, 이를 오름차순으로 정렬하는 코드. 
위와 마찬가지로 반복할 횟수와 빈 리스트를 만들고, a만큼 반복하여 c값을 입력받은 후 b에 추가하고, sort 함수를 사용하여 오름차순으로 정렬했다. sort의 reverse값을 활용하여 내림차순으로 만들거나, sorted를 통해 b와는 별개로 하는 새로운 리스트를 만드는 것도 가능하다.
> week 6 : 최재우 과제 제출

- 민세라/6주차/6-1.py
- 민세라/6주차/6-2.py
- 민세라/6주차/6-3.py
[6-1]
회문을 판별하기 앞서 문자열을 입력받은 후 홀수면 가운데에 있는 문자열을 지움.
for문을 통해 0번째,-1번째(마지막)를 하나씩 증가시키면서 비교하면서 만약 같지 않다면 result에 false저장
아니라면 맨 처음에 result값에 true를 선언했기때문에 true를 출력하게됨.
[6-2]
n개의 숫자를 입력받는과정에서 0을 입력받으면 그 전에 있는 숫자를 지워야 하기때문에 pop()을 사용.
0이 아니라면 리스트에 추가됨. 그 후 for문을 사용해서 result에 li의 모든 값 더한 후 출력.
[6-3]
n개의 숫자를 입력 받아 n만큼 for문을 돌려 먼저 선언해둔 리스트에 정수 값 추가.
받은 정수들을 sort() 내장 함수를 통해 오름차순으로 정렬됨
for문으로 리스트의 값을 하나씩 출력.
> Week 6 : 민세라 과제 제출

- 이진서/6주차/6-1.py
- 이진서/6주차/6-2.py
- 이진서/6주차/6-3.py
6-1(수정)
s 라는 변수에 값을 입력받아 리스트에 저장 후 l1이라는 변수에 리스트를 저장한다. l2라는 변수에 l1의 데이터가 반대로 정렬된 리스트를 저장한다. 조건문을 이용해 l1과 l2가 같으면 True, 다르면 False를 출력하게 한다.
> Week 6: 이진서 과제 제출

- 류지호/6주차/6-1.py
- 류지호/6주차/6-2.py
- 류지호/6주차/6-3.py
> Week 6 : 류지호 과제 제출

- 남지선/6주차/6-1.py
- 남지선/6주차/6-2.py
- 남지선/6주차/6-3.py
해결되지 않는 문제, 오류
-> 없습니다.
과제에 대해 궁금한 점
-> 없습니다.
추가적인 궁금점
->없습니다.
6-1
->단어를 한 글자(문자char)씩 리스트에 저장한 다음 step 값을 -1로 주어 역순으로 저장되게 해주었습니다. 역순으로 저장된 리스트와 원래 입력 받았던 단어가 있는 리스트가 같을 경우에 True를 출력하게 했습니다.
6-2
-> 0이 아닌 숫자를 받으면 스택에 저장하고 0을 입력 받으면 스택에 가장 위에 있는 값을 pop을 통해 빼는 방법으로 코드를 작성했습니다.
6-3
->숫자를 입력 받아 리스트에 저장한 뒤 sort를 통해 오름차순으로 정렬되게 해주었습니다.
> Week 6 : 남지선 과제 제출

- 김진우/6주차/6-1.py
- 김진우/6주차/6-2.py
- 김진우/6주차/6-3.py
6-1:단어를 입력받고 반복문을 이용해 입력받은 단어의 반만큼을 확인함 -> 회문인지 판단할때 앞과뒤의 문자를 하나씩 비교하기위해서 각문자를 비교해서 서로 같으면 회문(true),서로 같지 않다면 회문이아님 (false).
6-2:사용자로부터 카드의 개수를 입력받는다.cards 리스트는 카드를 담는 리스트이고, total_sum 변수는 카드에 적힌 숫자의 합을 저장하는것이다.반복문을 사용하여 카드의 개수만큼 숫자를 입력받는다.각 숫자를 입력받을 때, 만약 입력받은 숫자가 0이라면:
cards 리스트에서 가장 최근에 추가된 카드를 빼내어 removed_card 변수에 저장하고,total_sum에서 removed_card의 값을 뺀다.
그렇지 않으면, 입력받은 숫자를 cards 리스트에 추가하고, total_sum에 입력받은 숫자를 더한다.
6-3:사용자로부터 N을 입력받은후 반복문을 통해 N번의 반복을 진행한다. 각 반복에서는 사용자로부터 숫자를 입력받고, 이를 numbers 리스트에 추가한다.sorted 함수를 사용하여 numbers 리스트를 오름차순으로 정렬하여 sorted_numbers 변수에 저장하고
반복문을 통해 sorted_numbers 리스트를 순회하면서 각 숫자를 출력한다. 이를 통해 오름차순으로 정렬된 숫자들이 한 줄에 하나씩 출력되게된다.
> Week 6 : 김진우 과제 제출

- 이원석/5주차/5-1.py
- 이원석/5주차/5-2.py
- 이원석/5주차/5-3.py
- 이원석/6주차/6-1.py
- 이원석/6주차/6-2.py
- 이원석/6주차/6-3.py
6주차 과제입니다. 개선할 점이 있다면 알려주시면 감사하겠습니다.
<코드 리뷰>
6-1
#한글자씩 읽어야 한다 , for, 앞에서 한번 읽고, 뒤에서 한번 읽고 다른 것을 만나면 리턴0, 같으면 리턴1
6-2
6-3
#for문, 비교 연산자, 큰 값 스택에 저장, while pop
#스택보다 큐가 더 적절
> Week:6 이원석 과제제출

- 정지훈/6주차/6-1.py
- 정지훈/6주차/6-2.py
- 정지훈/6주차/6-3.py
1.
for 문을 이용하여 첫 단어 끝 단어부터 시작해서 가운데 단어까지 비교함. 단어가 같으면 아무 일도 일어나지 않고 단어가 다르면 num 을 1 증가시킴 num이 0일 경우( 단어가 같음)만 True 가 나오고 num이 0이 아니면 바로 False 가 나온다.
2.
for 문을 이용하여 숫자를 입력한 만큼 숫자를 a에 집어넣는다. 숫자가 0일 경우 0을 입력하기 전에 넣은 숫자를 삭제하고 a의 len이 바뀌므로 index도 감소시킨다. b가 0이 아니면 숫자를 a에 집어넣고 a의 len 이 증가되므로 index도 증가시킨다.
3.
for 문을 이용하여 숫자를 받은 후 sort를 이용하여 오름차순으로 정렬시킨다. sort를 사용해도 중복은 제거되지 않으므로 while 문을 써서 인덱스를 비교하며 자기 자신과 다음 숫자를 비교하여 같으면 자기 자신을 지워 중복을 없앤다.
> Week 6 : 정지훈 과제제출

- 김부연/6주차/6-1.py
- 김부연/6주차/6-2.py
- 김부연/6주차/6-3.py
6-1
word 에  화문인지 아닌지  판별하고 싶은 단어 입력받는다. is_palindrome은 화문인 경우 True를 출력하기 위해 지정해 주었고 word의 길이의 반만큼 돌면서 첫 번째 글자와 마지막 글자부터 서로 같은지 비교하고 거짓인 경우는 반복문을 빠져 나오게 만들었다.
6-2
숫자를 입력받을 배열인 num 배열을 설정하고 숫자를 몇개 입력받을지 input 통해 입력받은 것 N에 저장한다. 그리고 반복문을 N번 돌면서 입력받은 숫자가 0이 아니면 계속 추가하고 그게 아니면 pop()통해 맨 끝에 들어온 부분 제거한다. 그리고 나서 남은 숫자들의 합을 sum 통해 구하고 값 출력한다.
6-3
N 통해 숫자 몇개 입력받을 것인지 입력받은 거 저장하고 숫자들을 저장할 number_list를 만들었다. N번 동안 반복문 돌면서 리스트에 숫자 추가 추가하고 list(set(number_list)) 통해 입력받은 숫자들을 정렬하고 그 것들을 final_numbers에 저장하고 이를 최종적으로 반복문 돌면서 출력한다.
> Week 6 : 김부연 과제 제출

- 최민규/6주차/6-1.py
- 최민규/6주차/6-2.py
- 최민규/6주차/6-3.py
6-1:
a에 문자열 입력
a를 뒤집은 문자열과 a를 비교하여 같을 시 True 출력 아니면 False
6-2:
정수 k 입력 받아 k만큼 정수 입력
입력 받은 정수가 0이 아니면 배열에 추가하고 0일 경우 배열에서 pop
배열에 남은 정수의 합 출력
6-3:
n정수 입력
n만큼 정수 입력 받아 배열에 저장
배열을 오름차순으로 정렬 후 하나씩 출력
> Week 6 : 최민규 과제 제출

- 김민정/6주차/6-1.py
- 김민정/6주차/6-2.py
- 김민정/6주차/6-3.py
'_'는  반복문을 반복시킬때 변수 없이 반복문을 실행하는것을 의미합니다. K번 만큼 반복을 실행할때 반복문에서 변수를 사용하지 않고 반복문을 실행합니다.
> week 6: 김민정 과제 제출

- 이윤지/6주차/6-1.py
- 이윤지/6주차/6-2.py
- 이윤지/6주차/6-3.py
1. 사용자 지정 함수를 통해 입력된 문자열을 거꾸로 뒤집어 저장함. (a[::-1]) 이후 처음 입력된 문자열과 비교해 결과를 출력함. (print 함수 안에 비교 연산자를 사용하면 참/거짓을 판단해 결과를 출력함)
2. 처음 입력한 숫자만큼 반복함. 카드의 값을 계속 입력 받고, 입력된 수가 0일 경우 마지막 수를 pop으로 삭제함. 반복이 종료되면 sum 함수를 이용해 남아있는 수를 모두 더해 출력함.
3. 처음 입력한 숫자만큼 반복함. 리스트에 넣을 숫자를 계속 입력 받고, 만약 이전에 입력된 숫자라면 "중복된 숫자를 입력할 수 없다"는 안내를 출력한 후 중복되지 않은 숫자를 입력할 때까지 반복함. 반복 종료 후, set 함수를 이용해 남아있는 값들을 정렬해 출력함.
> Week 6 : 이윤지 과제 제출

- 박지원/6주차/6-1.py
- 박지원/6주차/6-2.py
- 박지원/6주차/6-3.py
6-1번 : range(3)을 사용해 3번의 단어 입력을 반복하게 한다. word[::-1]은 문자열 전체에서 인덱스를 1씩 감소시켜 요소를 가져오므로 문자열을 반대로 뒤집는다.
6-2번 :  N값을 입력받고 N은 카드의 수를 나타낸다. if(n == 0):    cards.pop을 써 n이 0이라면 cards 리스트에서 마지막 카드를 없애고,  else:   cards.append(n)을 써서 n이 0이 아니라면 리스트에 n을 추가한다.  카드 리스트에 남아 있던 숫자들을 모두 더하고 출력한다.
6-3번 : N개의 숫자를 입력받아 number 리스트에 저장하고 numbers.sort() 코드를 써 리스트 안에 있는 수들을 오름차순으로 정렬한다.
> Week 6 : 24박지원 과제 제출

- 김승재/6주차/6-1.py
- 김승재/6주차/6-2.py
- 김승재/6주차/6-3.py
6-1. 단어를 입력 받은 후 해당 단어를 문자로 입력받은 후 리스트에 저장. reversed 함수를 사용해 리버스한 결과가 기존 리스트와 같으면 TRUE, 다르면 FALSE 출력
6-2. 자료구조 개념 중 스택을 사용하기 위해 push 함수와 pop 함수를 정의. 숫자를 입력 받을 횟수를 입력받아 해당 값만큼 반복문을 실행하면서 값을 입력받음. 리스트를 생성하여 값을 입력받고 만약 입력된 값이 0일 경우 pop 함수를 통해 기존에 있던 값을 없앰. 반복문 실행이 끝났을 시 stack 배열에 있는 값을 모두 더해 출력
6-3. 숫자를 입력받아 해당 값만큼 반복문을 실행하면서 숫자를 입력받음. 반복문 실행이 다 끝났을 시 크기대로 나열하기 위해 리스트에 저장되어 있는 값을 앞에서부터 비교한 후 만약 리스트 앞에 위치한 값이 뒤에 위치한 값보다 값이 크다면 해당 두 수의 위치를 바꾸어줌. 이중 반복문을 통해 처음부터 끝까지 비교해준 후 크기가 작은 순서대로 나열된 리스트의 결과를 출력함
> Week 6 : 김승재 과제 제출

- 김수민/6주차/6-1.py
- 김수민/6주차/6-2.py
- 김수민/6주차/6-3.py
1번 문제 : 원하는 단어를 입력 받은 후 단어를 첫번째 반복문을 통해 한 글자씩 큐에 저장 시킨다. 그 후 두번째 반복문을 통해 큐에 큐에 저장된 단어들을 양 끝에서부터 비교하고 문제가 없으면 True를 그대로 출력, 문제가 있으면 False로 바꾸고 break로 반복문을 빠져나온다.
2번 문제 : 우선 원하는 카드의 갯수를 입력하고 반복문을 통해 그 갯수 만큼 반복시킨다. 반복하면서 입력된 숫자들을 스택에 하나씩 저장시키다가 0이 입력되면 입력된 숫자 하나를 삭제한다 스택은 가장 최근에 저장된 요소가 지워지므로 바로 전에 입력한 숫자가 지워진다. 반복을 끝낸 후 최종적으로 결정된 요소의 수 만큼 반복시키며 저장된 요소들을 더한 후 출력한다.
3번 문제 :  우선 원하는 숫자의 갯수를 입력받은 후 그 수 만큼 반복시키며 list에 저장시킨다. 그 후 list.sort()로 리스트의 요소들을 오름차순으로 정리하고 반복문을 통하여 리스트의 요소들을 하나씩 출력한다.
> Week 6 : 김수민 과제 제출

- 고석훈/6주차/6-1.py
- 고석훈/6주차/6-2.py
- 고석훈/6주차/6-3.py
6-1 사용자에게 단어를 입력받아 단어의 길이의 반만큼 반복하고 반대쪽은 w[-1] 부터 i를 증가 시켜 인덱싱하여 회문을 판별한다.
6-2  입력된 숫자가 0일 경우에는 가장 최근에 추가된 카드를 제거하고, 0이 아닌 경우에는 카드를 큐에 추가한다. 마지막에는 카드에 적힌 숫자의 합을 구하여 출력한다.
6-3  주어진 개수만큼 숫자를 입력받고 리스트에 저장한 후, 리스트를 오름차순으로 정렬한다.
> Week 6 : 고석훈 과제제출

- 이보윤/6주차/6-1.py
- 이보윤/6주차/6-2py
- 이보윤/6주차/6-3.py
코드리뷰6-1.회문 판별값을 저장할 변수, 초깃값은 True이다,
0부터 문자열 길이의 절반만큼 반복하고
왼쪽 문자와 오른쪽 문자를 비교하여 문자가 다르면
회문이 아니다.그 후 회문 판별값 출력한다
코드리뷰 6-2. 사용자로부터 입력받은 숫자의 개수를 먼저 묻는다.
그런 다음 사용자가 입력한 개수만큼 반복하면서 숫자를 입력받아 리스트에 저장한다.
마지막으로 리스트에 저장된 숫자들의 합을 계산하여 출력한다.
코드리뷰 6-3.입력한 정수를 리스트에 저장하고,
리스트를 정렬한 후에는 오름차순으로 정렬된 숫자를 각 줄에 출력하고
마지막으로, 정렬된 숫자들을 공백 없이 출력한다
> week 6 : 이보윤 과제 제출

- 박관호/6주차/6-1.py
- 박관호/6주차/6-2.py
- 박관호/6주차/6-3.py
#1번 문제 :  수업자료에 있는 큐를 사용했다. 먼저 org_queue = deque() 로 큐 초기화. 그 다음에 입력 받을 단어를 value 로 저장한다. 여기서 나는 1번 문제를 해결하기 위해서는 문자열의 각각의 단어를 큐에다가 집어넣고 반대로 저장된 큐를 비교하여 같으면 트루, 다르면 펄스로 출력하려고 생각을 했고 이거에 맞게 코드를 작성해 보았다. 일단 가장먼저 입력받은 문자를 큐에다가 하나씩 저장하기 위해서 문자열 for 루프 돌면서 한 글자씩 큐에다가 .append 했다. 그 다음에 리버스 큐를 하나 생성에서 오리진 큐를 복제한뒤 리버스 큐를 .reverse 메소드 해서 반대가 되게 설정했다. 그다음에 if문 돌려서 참 거짓 판단.
#2번 문제 : 이것도 큐를 사용해보았다. 2번 문제가 처음에 설명을 읽었을때 뭔 말하는건지 조금 헷갈렸지만 그냥 간단히 얘기해서 0 이 나오면은 최근꺼를 뺀다 라는 것이였다. 근데 수업자료로 올린거는 .popleft 밖에 없어서 살짝 당황했지만 vs code 자동완성에 .pop도 있어서 오 이건가 해서 써봤는데 최근에 집어넣었던게 빠졌다. 그래서 수월하게 진행 할 수 있었다. 똑같이 큐 초기화 하고 최대숫자 input하고 for 루프 최대 숫자 돌면서 숫자 입력. 여기서 if문으로 받은 숫자가 0이면 팝, 아니면 .append 마지막으로 프린트.
#3번 문제 : 수업자료 list편에 있는 .sort 메소드를 활용했더니 금방 풀렸다.
숫자값 수를 input으로 받고, 이 숫자값 수를 for 루프로 돌면서 숫자를 받아야 하므로 list 생성. 그 다음에 계획했던 대로 …
> week 6 : 박관호 과제 제출

- 이유림/6주차/6-1.py
- 이유림/6주차/6-2.py
- 이유림/6주차/6-3.py
6-1
회문인지 판별할 문자를 word로 받고 회문 판별값을 저장할 변수를 a로 두고 초깃값은 true로 한다. 그리고 0부터 문자열 길이의 절반만큼 반복하는 것을 for문을 사용하고 if문을 사용해서 왼쪽 문자와 오른쪽 문자를 비교해서 문자가 다르면 a를 False로 바꾼다. 그리고 회문 판별값을 출력한다.
6-2
입력 받을 숫자의 개수를 K로 받고 숫자를 저장할 리스트 스택을 만들고 if문을 사용해서 0이 입력되면 가장 최근에 추가된 숫자를 제거하고 0이 아닌 숫자는 스택에 추가한다. 그리고 스택에 남아있는 모든 수의 합을 계산해서 결과를 출력한다.
6-3
N에 수의 개수를 입력받는다. 그리고 공백 리스트를 하나 생성하고 for문을 사용해 입력받은 수만큼 반복한다. 그리고 num에 각각 한 줄씩 수를 입력받고 입력받은 수를 리스트 li에 추가한다. 그리고 li.sort를 사용해 값을 모두 입력받은 리스트를 오름차순으로 정렬한다. 그리고 정렬해준 리스트의 수를 하나씩 출력한다.
> Week 6 : 이유림 과제 제출

- 이재원/5주차/5-1.py
- 이재원/5주차/5-2.py
- 이재원/5주차/5-3.py
- 이재원/6주차/6-1.py
- 이재원/6주차/6-2.py
- 이재원/6주차/6-3.py
6-1
회문인지 판별할 단어를 입력받는다
if문을 사용하여 입력받은 단어와 뒤집은 단어가 똑같다면
true를 출력하고 아니라면 false를 출력한다
6-2
변수 k에 정수를 입력받고
카드라는 리스트 생성
for문을 사용하여 k만큼 반복한다
변수o에 카드번호를 입력받고
if문을 이용하여 o가 0이라면 pop을 통해 마지막 숫자를 빼고
0이 아니면 append를 통해 리스트에 더한다
for문을 이용하여 cards리스트의 모든 요소를 더한 뒤 출력한다.
6-3
변수 N에 수를 입력받고, num이라는 리스트 생성
for문을 이용하여 N번 반복한다
n이라는 변수에 정수를 입력받고,
append를 이용하여 num 리스트에 저장한다
sort를 이용하여 num리스의 수를 정렬하고 출력한다.
> WEEK6 : 이재원 과제 제출

- 김정우/6주차/6-1.py
- 김정우/6주차/6-2.py
- 김정우/6주차/6-3.py
6-1
1 : 단어를 입력 받고 a변수에 저장
3~6 : a를 뒤집었을 때 a 하고 같으면 True 다르면 False를 출력
6-2
1 : 정수를 입력 받아 변수 a에 저장
2 : 빈 리스트 c 생성
3 : a번 반복
4 : b를 입력 받아 정수로 저장
5~8 : b가 10보다 작고 0보다 크면 리스트 c에 저장 그 외는 최근 저장한 리스트 삭제
9 : 리스트 안에있는 값을 모두 더해 출력
6-3
1 : 정수를 입력 받아 정수 형태로 변수 a에 저장
2 : 빈 리스트 b생성
3~5 : 변수를 입력받아 리스트 b에 넣는 걸 a 번 반복
6 : 리스트 b를 오름차순으로 정렬
7 : 리스트b를 0부터 a까지 반복해서 출력
> Week 6 : 김정우 과제 제출

- 이학준/6주차/6-1.py
- 이학준/6주차/6-2.py
- 이학준/6주차/6-3.py
> Week6: 이학준 과제 제출

- 김진영/6주차/6-1.py
- 김진영/6주차/6-2.py
- 김진영/6주차/6-3.py
6-1
a = input("입력하시오 : ") 
r = True
: 문자열을 입력 받고 회문 여부를 저장하는 변수를 True로 초기화 한다
for i in range(len(a)//2):
: 문자열의 반만큼 반복시킨다
if a[i] != a[-1-i]:
r = False
break
: 문자열을 비교하여 다르면 회문이 아닌것을 나타내는 변수를 설정하고 반복문을 종료시킨다
print(r)
: 출력
6-2
k = int(input())
c = []
: 카드의 개수를 입력받고 카드를 저장할 리스트를 만듦
for i in range(k):
n = int(input())
: 카드의 개수만큼 반복시키고 카드의 숫자를 입력 받는다
if n == 0:
c.pop()
: 입력 숫자가 0이면 리스트에서 최근에 추가된 카드를 제거
else:
c.append(n)
: 입력 숫자가 0이 아니면 입력 숫자를 리스트에 추가
print(sum(c))
: 리스트에 있는 숫자들의 합을 계산하여 출력
6-3
n = int(input())
num = []
: 정수를 입력 받고 정수를 저장할 리스트를 생성
for i in range(n):
num.append
: 입력된 정수의 개수만큼 반복한다
(int(input())) 
: 정수를 입력 받아 리스트에 추가한다
num.sort() 
: 리스트를 오름차순으로 정렬
print(num)
: 리스트 출력
> week 6 : 김진영 과제 제출

- 문준호/1주차/1-1.py
- 문준호/6주차/6-1.py
- 문준호/6주차/6-2.py
- 문준호/6주차/6-3.py
**1. 회문 확인하기**
우선 queue에 입력을 받습니다.
그리고 queue의 길이 / 2 만큼 queue의 왼쪽과 오른쪽을 pop하여 같으면, 계속 진행하며 아니면, 회문이 아니라는 말을 print합니다
이 결과, 단어가 홀수 개의 글자로 구성되어있으면 가운데 하나만 남기고, 짝수라면 모두 pop하여 확인하는 꼴이 됩니다.
이 과정이 전부 수행되었다면, 회문이라고 출력합니다.
**2. 카드 게임**
0이 입력되면 pop하고, 0이 아닌 수가 입력되면 append합니다.
그리고 최종적으로 sum이라는 변수에 queue에 담긴 모든 값을 pop하며 더하고, 이를 출력합니다.
**3. 숫자 정렬**
_실수로 dequeue가 아닌 list로 문제를 풀었습니다._
1. 숫자 x를 입력받습니다.
2. 현재 리스트의 길이 만큼 for문을 돌며 수를 비교합니다.
만약, x가 리스트에 담긴 수보다 크다면, 다음 칸으로 이동합니다.
이때, 다음칸이 존재하지 않으면, append하여 x를 리스트에 추가합니다
만일, x가 작거나 같으면, 그냥 그곳에 insert하게 됩니다.   
그리고 최종적으로 리스틀 출력합니다
> Week 6 : 문준호 과제 제출

- 김지원/6주차/6-1.py
- 김지원/6주차/6-2.py
- 김지원/6주차/6-3.py
> Week 6 : 김지원 과제 제출

- 이태규/6주차/6-1.py
- 이태규/6주차/6-2.py
- 이태규/6주차/6-3.py
6-1:문자열 대소문자 구분 없애기,문자열 반만큼 순환,문자열 양끝부터 비교,다른문자 발견되면 false반환,다른문자 없으먼 true 반환,
6-2:빈 리스트 q생성,정수 k입력,k번반복하면서 정수 qu입력,qu가 0이아니면 q에 해당값 추가,qu가 0이면 q에서 마지막 요소 제거,반복완료되면 q합산 후 result 출력
6-3:정수 num입력, num list생성,num번 반복하면서 정수 a입력, num list 오름차순으로 정리,출력
> week 6 : 이태규 과제 제출

- 김국현/6주차/6-1.py
- 김국현/6주차/6-2.py
- 김국현/6주차/6-3.py
6-1: 받은 string을 list로 만들고 list를 reverse 시켜서 reverse시켜도 같으면 true 아니면 false
6-2: collections의 deque함수를 이용해 queue를 만들고 append와 proleft 메서드를 이용하여 선입선출을 함
6-3: sorted함수를 이용하여 받은 수들을 저장한 list를 오름차순으로 출력함
> Week 6 : 김국현 과제 제출

- 최인규/6주차/week6-1.py
- 최인규/6주차/week6-2.py
- 최인규/6주차/week6-3.py
코드에 대한 설명은 각 코드에 주석으로 필요한 부분에 달아 놓았습니다 !
> Week 6 : 최인규 과제 제출

- 조항준/7주차/7-1.py
> Week 7 : 조항준 과제 제출

- 김준호/5주차/5-1.py
- 김준호/5주차/5-2.py
- 김준호/5주차/5-3.py
- 김준호/6주차/6-1.py
- 김준호/6주차/6-2.py
- 김준호/6주차/6-3.py
5-1
if 문으로 0~100 범위의 5의 배수인 정수가 아닌 수 배제
n 이 50 미만인 경우 값 50으로 고정
후에 5로 나눠서 평균값 산출
5-2
^으로 가운데 정렬하려 하였으나 상수로만 가능하고 변수로는 불가능 (n을 넣어서 전체 공간을 만들어 주려 했으나 변수로는 포매팅 불가능)
따라서 앞에 띄어쓰기를 추가해서 가운데 정렬 트리 구현 (n(총 인덱스)-i(해당 줄의 인덱스)-1)
5-3
윷 정보 입력 후 리스트에 저장
리스트 클래스의 count 함수 활용하여 0의 개수를 뽑고 if 문을 통해 어떤 윷인지 판정 가능
6-1
-----reverse() 함수는 한 블록에서만 사용 가능함 유의-----
그 후 순서 역정렬한 리스트 문자열 변환 (list 함수 사용)
6-2
if를 통해 0~9 숫자 입력 제한
0을 뽑으면 pop
이 때 append(push)는 if 문들로 조건 확인 후 시행 함에 유의 (0을 입력하고 푸시/팝을 하면 리스트의 정보 변화가 없게 됨)
6-3
입력 회수를 입력받고 list class의 sort 함수 활용
> Week 6 : 김준호 과제 제출

- 서민혁/6주차/6-1.py
- 서민혁/6주차/6-2.py
- 서민혁/6주차/6-3.py
6-1:입력한 문자를 reverse를 사용하여 원래 문자와 비교하여 판변하는 코드이다. reverse 함수는 자주 쓰이기 때문에 비교적 편하게 풀었다.
6-2:처음으로 pop을 이용해본 코드였다. 그동안 파이썬을 사용할 때 리스트는 많이 사용해 보았지만, 큐는 사용 경험이 없었는데, 이번 기회에 큐 자료 구조에 대해 알아 볼 수 있어 유익한 시간이였다. 데이터를 쌓으며 관리하는 방식의 프로그램이라면 큐를 자주 사용할 수 있을 것 같다.
6-3:sort함수를 이용하여 쉽게 오름차순 정렬을 할 수 있었다. 오름차순 정렬은 파이썬에서 오랜만에 써보았는데, 다른 언어보다 오름/내림차순 정렬에 훨씬 편리하다고 느꼈다.
> Week 6 : 서민혁 과제 제출

- 김동현/1주차/w1.py
- 김동현/6주차/6-1.py
- 김동현/6주차/6-2.py
- 김동현/6주차/6-3.py
다음부터는 코드 덩어리 각각에 충분한 고민을 해보도록 하겠습니다. 지적해주셔서 감사드립니다.
1번 문제는 문자열의 길이를 이용했습니다. len을 통해 문자열의 길이를 파악했고, 첫 번째 character와 마지막 character의 비교를 시작으로 가우스 계산법처럼 비교를 진행하도록 하였고, 비교 진행 횟수는 홀수 갯수일 경우 (정가운데 character는 비교할 대상도 없고 할 필요도 없으므로)함수에 저장한 len의 1/2배(소숫점 이하 절삭) 만큼 진행하도록 하였습니다. 비교 도중 character가 다름이 인식되면 d 변수에 1을 더하도록 했고, 0의 값을 가졌던 d 가 0일 경우 ture, 0 초과일 경우 false를 출력하도록 했습니다.
2번 문제는 queue를 이용하려고 했으나 문제 조건상 가장 최근에 입력된 토큰을 pop시켜야 했으므로 queue의 특징인 '맨 앞 토큰부터 pop'을 만족하지 못해 불가피하게 queue를 이용하지 못했습니다. 우선 리스트 q에서 맨 마지막 토큰이 0인지의 여부를 물었고, 0일 경우에는 토큰 0과 "그 이전에 들어간 토큰을 pop"하도록 했습니다. 만약 리스트 내의 토큰이 두 개 이상이 아닐 경우 "그 이전에 들어간 토큰을 pop"은 작동하면 안되므로 if를 이용해 토큰이 두 개 이상일 경우에만 "그 이전에 들어간 토큰을 pop"가 작동되도록 했습니다. 맨 마지막 덧셈 부분은 range로 접근한 게 문제라고 생각되어 for문을 아예 지우고 sum을 이용했습니다.
+pop에 걸려 있던 불필요한 if를 제거하였습니다. 감사합니다.
3번 문제는 sort에 대해서 복습할 …
> Week 6 : 김동현 과제 제출

- 이찬혁/7주차/7-1.py
__init__으로 초기값 설정하게 하고
wh에 "너비 높이" 형태로 입력하고
가운데 띄어쓰기를 기준으로 split하여
w는 너비, h는 높이로 입력되고
rec은 class Rectangle에 w,h를 입력한 객체(?) 가 되고 area는 그 rec의 area_calc의 반환값(넓이), circum은 rec의 circum_calc의 반환값(둘레)가 되서 출력하면 끝입니다
> Week 7: 이찬혁 과제 제출

- 김동현/7주차/7-1.py
<용어 정리>
매개변수 == 인자(메서드 내의 변수) != 인수(특정한 값)
<Rectangle 클래스 내에 있는 메서드 __init__>
초기화 메서드로, 생성자라고도 합니다. 암묵적인 첫 번째 매개변수 self를 가지고 있습니다.
생성자는 클래스 내에서, 객체가 생성될 때 생성자 내의 코드를 자동으로 호출해주는 역할을 합니다.
해당 코드에서는 class 내의 지역변수를 area_calc()메서드와 circum_calc()메서드 내에서 사용할 수 있도록 해 줍니다.
<클래스 내의 인스턴스>
인스턴스는 클래스의 객체입니다.  해당 코드에서는 rec 가 유일한 인스턴스입니다.
<self(메서드의 암묵적인 첫 번째 변수)>
self는 변수가 메서드 __init__의 매개변수로써 인식될 수 있도록 해 줍니다. self는 메서드 내의 첫 번째 매개변수로, 이를 통해 변수를 정의해야만 메서드 내에서 변수를 사용할 수 있습니다.
메서드 밖에서는 self 변수가 없으므로, 메서드 외에서는 변수를 self를 통해 정의할 수 없습니다.
어디까지나 암묵적인 요소이므로 다른 형태로 변수를 정의해도 코드가 정상작동되나, 가독성 향상을 위해 self를 사용합니다.
<이외에 코드 리뷰>
코드 내의 두 메서드에서 넓이 변수(area)는 너비 변수(width)와 높이 변수(height)의 곱을 저장하도록 합니다.
이후 return을 통해 '메서드 내의 변수 area'를 메서드 값으로 반환합니다.
메서드 값으로 반환하는 작업을 건너뛸 시 메서드 외에서는 '메서드 내의 area 변수'에 입력한 값을 인식할 수 없으므로 area가 None인 …
> Week 7 : 김동현 과제 제출

- 류지호/7주차/7-1.py
> Week 7 : 류지호 과제 제출

- 이재원/7주차/7-1.py
사각형의 넓이와 둘레를 구하는 코드 중 Rectangle이라는 클래스의 인스턴스가 생성될 떄 필요한 속성인 높이와 폭을 정의한다.
> Week7: 이재원 과제 제출

- 김부연/7주차/7-1.py
> Week 7 : 김부연 과제제출

- 박관호/7주차/7-1.py
카톡에 올라온 페이지하고 유튜브도 찾아봐서 파이썬의 생성자에 대해서 공부했다. 하나의 클래스를 생성하고 거기에 init메소드를 사용해서 쓸 변수들을 초기화 할 수 있는 좋은 기능인 것 같다. 과제 진행중 18번 라인에 rec = Rectangle()이렇게 만 했는데 오류가 나서 고민을 했었다. 고민 끝에 안 사실은 입력받은 width와 height를 전달해줘야대는데 전달해 줄 곳이 없기 때문이였다.그래서 인자를 Rectangle함수 안에 넣었더니 정상 실행이 됐다.
#궁금한 점 : 없음
#바라는 점 : 없음
#어려운 점 : 없음
> week 7 : 박관호 과제 제출

- 이유림/7주차/7-1.py
7-1
사각형의 나타내는 'Rectangle'을 정의한 후에, 사각형의 높이와 너비를 나타내는 'width'와 'height'을 변수로 한다. 그리고 '__init__'를 사용해서 객체를 초기화한다. 그리고 'area_calc'는 너비와 높이를 곱하여 사각형의 넓이를 계산하고 반환한다. 'circum_calc'는 너비와 높이를 더한 후 2배 한 값을 변환하여 사각형의 둘레를 계산한다. 그리고 넓이와 둘레를 계산하고 출력한다.
> Week 7: 이유림 과제 제출

- 김태현/7주차/7-1.py
보안입니다. 
__self__ 생성자를 정의하고 넓이와 높이를 정의했습니다. 
__init__ 매서드를 사용해 생성된 객체를 초기화 했습니다.
> Week 7 : 김태현 과제 제출

- 정원준/7주차/7-1.py
> Week 7 : 정원준 과제 제출

- 김민정/7주차/7-1.py
def __init__(self, width, height):
self.width = width
self.height = height
에서  __init__이라는 메서드는 파이썬에서 특별하게 약속된 메서드 가운데 하나로, 초기화 메서드라고한다 합니다..  어떤 클래스의 객체가 만들어질 때 자동으로 호출되어서 그 객체가 갖게 될 여러 가지 성질을 정해주는 일을 하면서
self는 클래스의 인스턴스를 나타냅니다. 클래스 인스턴스란 클래스를 이용하여 실제로 만들어진 객체를 의미하고  self.width와 self.height는 해당 클래스의 인스턴스가 갖는 속성입니다.
width와 height는 __init__ 메소드의 매개변수로, 객체를 생성할 때 사용자로부터 입력받은 값을 받아와서 인스턴스의 속성으로 설정하고, 이 코드는 객체가 생성될 때 입력받은 가로 길이와 세로 길이를 해당 객체의 속성으로 설정하는 역할을 합니다!
> week 7: 김민정 과제 제출

- 이원석/11주차/11-1.py
- 이원석/6주차/6-3.py
- 이원석/7.5주차/init.py
- 이원석/9주차/test.py
#인공신경망의 원리가 행렬의 곱으로 표현할 수 있으므로 행렬의 곱을 구현
> Week 11: 이원석 과제제출

- 11주차/11-1.py
입력이라는 새로운 데이터가 들어감 3과 5가 먼저 들어감 3에서 화살표가 2개, 5에서도 화살표가 2개 3에서 2만큼 곱하고 다음으로 넘겨줌 5에서 3만큼 곱하고 다음으로 넘겨줌 
3에서 4만큼 곱하고 다음으로 넘겨줌 5에서 -5만큼 곱하고 다음으로 넘겨줌
두번에 나눠서 하면 더 정확한 값을 가짐 weight는 가중치를 뜻함
weight_output은 출력에 대한 가중치 
(1, 1)인 [21]와 (1, 1)인 [2]를 곱해서 42, (1, 1)인 [-13]와 (1, 1)인 [7]를 곱해서 -91 을 더한 42+-91=-49로 -49가 나옴
> Week 11: 김세현 과제 제출

- 이윤지/11주차/11-1.py
np.array 생성 [3, 5]
노드에 각각 가중치 [2, 3]을 곱함
-> [3]x[2] + [5]x[3] = 21
노드에 각각 가중치 [4, -5]를 곱함
-> [3]x[4] + [5]x[-5] = -13
최종 예측값을 구하기 위해 가중치 [2, 7]을 곱함
-> [21]x[2] + [-13]x[7] = -49
> Week 11 : 이윤지 과제 제출

- 문준호/11주차/11-1.py
input_data로 [2,3] 데이터가 들어옵니다. 
그리고 가중치가 곱해져서 각 퍼셉트론에서 스칼라 값을 띄게 되고
여기서 output_weight가 최종적으로 곱해지고 더해져서 예측 결과 값이 나옵니다.
선형대수로 연산을 표기하려고 해보니 알게된 사실인데
hidden 0과 hidden 1이 열의 인덱스 번호를 의미하는 것이며
2x2인 행렬에 1x2인 행렬이 곱해져서, 1x2인 행렬이 나오는 것이였습니다.
이 요소들은 각 퍼셉트론에 할당된 스칼라 값이며, 이 값이 각각 output_weight가 곱해져서 더해져, 결과값이 나오는 것이였습니다.
> Week 11: 문준호 과제 제출

- 윤정아/11주차/11-1.py
연결된 노드와 간선의 숫자를 각각 곱한 후 더하면 다음 노드의 값을 구할 수 있습니다.  연산식을 하단에 작성하겠습니다!
연산식
3 * 2+5 * 3=21
3 * 4+5 *-5=-13
21 * 2+-13 * 7=-49
> Week 11 : 윤정아 과제 제출

- 장소원/11주차/11-1.py
numpy 라이브러리를 호출한다
input_data로 첫 행렬 지정(수정 불가)
weight_hidden_0과 weight_hidden_1로 행렬 곱 계산
3 x 2 + 5 x 3 = 21 / 3 x 4 + 5 x -5 = -13 
hidden_0_value와 hidden_1_value로  행렬 곱 저장
print로 hidden layer 출력
weight_output으로 출력에 대한 가중치를 곱한 것(21 x 2 = 42 / -13 x 7 = -91 )을 output에 저장 
output 출력(-49)
> Week 11 : 장소원 과제 제출

- 권우진/11주차/11-1.py
[3, 5]이라는 1행 2열의 행렬에서 가중치 [[2], [3]]과 [[4], [-5]] 2행 1열 행렬 두 개를 곱하면 [21]과 [-13]이라는 1행 1열이 나오고나서 [[2], [7]]이라는 행렬을 곱하면 -49라는 값이 나옵니다.
> Week 11 : 권우진 과제 제출

- 서민혁/11주차/11-1.py
처음 인풋의 경우 [3,5]이라는 행렬을 가지고 시작한다. 첫 가중치는 [2,3], 두번째 가중치는 [4, -5] 행렬이 존재하여 이는 인풋과 행렬곱을 하게 된다. 따라서 첫번째 은닉층에는 3*2+5*3=21 이라는 값이 들어가고, 두번째 은닉층에는 3*4+5*(-5)=-13 이라는 값이 들어간다. 이후 결과 가중치는 [2,7]이므로, 21*2+(-13)*7=-49로 예측값은 -49가 나오게 된다.
numpy로 간단하게 기본적인 인공신경망 구조를 연습해볼 수 있어 흥미로웠다.
> Week 11 : 서민혁 과제 제출

- 김용빈/11주차/11-1.py
코드 리뷰
input_data 란 변수에 np,array 배열을 사용해 [3,5] 라는 1x2 행렬을 입력합니다. 그 후 입력 값에 곱해지는 매개변수 값은 각각 weight_hidden_0과 weight_hidden_1 에 [2,3] 과 [4,-5]라는 가중치를 곱해준다. 이때 행렬 곱을 위해 입력 값 * 가중치를 한 후 sum() 으로 깊어진 행렬의 각각의 값을 구한다. 이렇게 나온 hidden layer의 합을 구하면 예측값이 -49가 나오게 된다. 또한 첫 번째 print문의 결과로 21,-13이 나오게 된다. 이는 hidden layer의 값이다.
> 11 Week : 김용빈 과제 제출

- 정원준/11주차/11-1.py
[3,5]라는 1행 2열에 [2,3],[4,-5]라는 2행 1열의 가중치를 곱한후 마지막에 [2,7]이라는 2행 1열의 가중치를 곱한다.
따라서 -49라는 결과값이 출력된다
> Week 11 : 정원준 과제 제출

- 민세라/11주차/11-1.py
입력값[3,5]을 받아온 후 1행 2열의 값 [2,3] 으로 값 21이 나오고 1행2열의 값 [4,-5]으로 값 -13이 나옴 = [21, -13] 나온 값[21,-13]에 값 [2,7]로 값 -49가 나옴.
> Week 11 : 민세라 과제 제출

- 김동현/11주차/11-0.py
- 김동현/11주차/11-1.py
- 김동현/9주차/9-1.py
1행: 
numpy를 np로 간단하게 쓸 수 있도록 import 해 줍니다
3행: 
Input 층의 노드에 각각 3과 5를 저장합니다
5~6행: 
Hidden Layer 층의 첫 번째 노드에 곱할 가중치는 2와 3
두 번째 노드에 곱할 가중치는 4와 -5로 지정합니다
7행: 
Output 층의 노드에 곱할 가중치를 2와 7로 지정합니다
9~10행: 
가중치_0은 Hidden Layer 층의 첫 번째 노드로 향하는 가중치를 정의한 단어이고
가중치_1은 Hidden Layer 층의 두 번째 노드로 향하는 가중치를 정의한 단어입니다
Input 층의 첫 번째 노드에 저장한 값(3)*첫 번째 가중치_0(2)+두 번째 노드에 저장한 값(5)*두 번째 가중치_0(3)를 hidden_0_value 에 저장합니다
Input 층의 첫 번째 노드에 저장한 값(3)*첫 번째 가중치_1(4)+두 번째 노드에 저장한 값(5)*두 번째 가중치_1(-5)를 hidden_1_value 에 저장합니다
11행: 
hidden_0_value와 hidden_1_value를 ,로 구분하여 출력합니다
13행: 
hidden_0_value에 저장한 값(21)*Output으로 향하는 첫 번째 가중치(2)+hidden_1_value에 저장한 값(-13)*Output으로 향하는 두 번째 가중치(7)를 output 에 저장합니다.
14행: 
output(-49)을 출력합니다
감사합니다
> Week 11 : 김동현 과제 제출

- 박관호/11주차/11-1.py
인공신경망에 대해서 학습했다. 여기서 input_data는 초기 실제 데이터. 변하면 안된다. 그리고 weight_hidden은 가중치, 즉 조절할 수 있다. 그다음에 weight_output 가중치를 입력해 output을 도출한다. 일단 먼저 [3,5]행렬에 [2, 3]행렬을 곱하고 (행렬의 곱 연산을 위해 행벡터와 열벡터의 곱으로 판단)그 요소들을 다 더한다. 이것을 1번 레이어 첫번째 노드에 저장. 그 다음으로 [3.5] 행렬을 [4, 5] 행렬과 곱하고 그 요소들을 더해서 두번째 노드에 저장. 그 후 마지막으로 첫번째 레이어에서 첫번째 노드는 최종 가중치 0번째 와 곱하고 두번째 노드를 최종 가중치 1번째 와 곱한다음 그 둘을 더한다. 그 값이 바로 output값이다.  처음에 *연산에 대해서 헷갈렸다. 근데 이것을 요소들의 곱이라 생각하니까 쉽게 이해 됬다.
> week11 : 박관호 과제 제출

- 이현준/11주차/11-1.py
초기 값 3에 가중치 2를 곱한 값과 초기 값 5에 가중치 3을 곱한 후 두 값을 더하여weight_ hidden_0값을 구한다. 초기 값 3, 5에 각각 가중치 4, 5를 곱한 후 더하여 weight_hidden_1을 구한다. 이후 weight_hidden_0과 weight_hidden_1에 각각 가중치 2, 7을 곱한 후 더하여 예측 값을 출력한다.
> Week 11 : 이현준 과제 제출

- 공현택/11주차/11-1.py
초기값 [3,5]에 가중치 [2,3]을 곱한다
(3*2)+(5*3)=21
초기값 [3,5]에 가중치 [4,-5]를 곱한다
(3*4)+(5*-5)=-13
[21,-13]에 가중치 [2,7]을 곱한다
(21*2)+(-13*7)=-49
> Week 11 : 공현택 과제 제출

- 이재원/인지스터디1/과제1
인풋 데이터를 3과 5로 변경해주고
두번째 위 동그라미에 2와 3이 향하고 있으니 가중치0에 [2,3]을 넣어준다
같은 방법으로 두 번쨰 아래 동그라미에 4와 -5가 향하고 있으니 가중치 1 [4,-5]를 넣어준다
마지막 아웃풋 가중치에 2와 7이 향하고 있으니 [2,7]을 넣어준다.
> Week 11: 이재원 과제 제출

- 류지호/11주차/11-1.py
> Week 11: 류지호 과제 제출

- 이진서/11주차/11-1.py
입력값에 [3,5]를 대입. Hidden_value_0에 적용되는 가중치에 [2,3]을 대입. Hidden_value_1에 적용되는 가중치에 [4,-5]를 대입.
결과값에 적용되는 가중치에 [2,7]를 대입.
> Week 11: 이진서 과제 제출

- 1주차.py
- 박지원(21)/11주차/11-1.py
- 박지원(21)/1주차.py
> Week 11: 박지원 과제 제출

- 박지원/11주차/11-1.py
코드리뷰 : 입력값을 [3,5]로 넣은후 weight_hidden_0 와 weight_hidden_1 가중치 값을 각각 지정한다.
hidden_0_value 는 은닉층값으로 input_data와 weight_hidden_0 곱의 합으로 계산된다 ( 21)
hidden_1_value 도 위와 같이 계산하면 -13이 출력된다.
output은 은닉층 값과 weight_output을 각각 곱하여 더하면 -49가 출력되게된다.
> Week 11 : 24박지원 과제 제출

- 김지성/11주차/11.py
입력층에 3,5 입력
첫 번째 은닉층에 3과 가중치 2를 곱한값과 5와 가중치 3을 곱한값의 합
두 번째 은닉층에 3과 가중치 4를 곱한값과 5와 가중치 -5를 곱한값의 합
출력층에 첫 번째 은닉층 값에 가중치 2를 곱한값과 두 번째 은닉층 값에 가중치 7을 곱한값의 합
빈칸 값 출력
> Week 11: 김지성 과제 제출 

- 남지선/11주차/11-1.py
해결되지 않는 문제, 오류, 과제에 대해 궁금한 점, 추가적인 궁금점 모두 없습니다.
> Week 11 : 남지선 과제 제출

- 김승재/11주차/11-1.py
위 코드는 행렬의 계산을 통해 간단한 인공신경망을 구현하는 코드이다. 행렬을 계산하기 위하여 numpy 라이브러리를 사용하였다. 처음 입력 데이터를 Input_data = np.array([3, 5])로 정의한다. 그리고 계산할 행렬을 weight_hidden 0 과 1로 정의한다. 그리고 출력 데이터를 weight_output = np.array([2,7])로 정의한다. sum() 함수를 이용하여 input_data*weight_hidden 값을 계산해둔다. 이때 hidden_0_value = (Input_data*weight_hidden_0).sum()의 계산 결과는 3*2 + 5*3 = 21이 되고, hidden_1_value = (Input_data*weight_hidden_1).sum()의 계산 결과는 3*4 + 5*(-5)  = -13이된다. 그리고 마지막으로 output = hidden_0_value*weight_output[0]+hidden_1_value*weight_output[1] 계산을 하면 21*2 + (-13)*7 = -49가 되므로 최종적으로 -49가 출력되게 된다.
> Week 11 : 김승재 과제 제출

- 컴공김태현/11주차/11-1
> Week11:컴공김태현 과제 제출

- 이보윤/11주차/week 11.py
import numpy as np 
input_data = np.array([3, 5]) //입력값을 배열로 정의
weight_hidden_0 = np.array([2, 3]) //입력값에 대한 가중치
weight_hidden_1 = np.array([4, -5])//입력값에 대한 가중치
weight_output = np.array([2, 7])//출력값에/ 대한 가중치
hidden_0_value = (input_data * weight_hidden_0).sum()//계산
hidden_1_value = (input_data * weight_hidden_1).sum()//계산
print(hidden_0_value, hidden_1_value, sep=', ')//계산값을 출력
output = hidden_0_value * weight_output[0] + hidden_1_value * weight_output[1]//입력값과 출력값의 가충치를 이용해 최종출력 계산
print(output)//최종 출력값을 출력
> week 11 : 이보윤 과제 제출

- 최재우/11주차/11-1.py
> Week11 : 최재우 과제 제출

- 김나윤/11주차/11-1.py
입력층 [3, 5]를 정의하고 첫번째 입력값 3에 대한 가중치 [2, 3], 두번째 입력값 5에 대한 가중치 [4, -5]와 출력층에 대한 가중치 [2, 7]을 정의한다.
입력층에 각 가중치를 곱하고 각각 더해 은닉층 [21, -13]을 정의한다.
첫번째 은닉층 값 21에 가중치 2를 곱하고 두번째 은닉층 값 -13에 가중치 7을 곱한다.
가중치를 곱한 두 값을 더해 출력층 [-49]를 정의한다.
> Week 11 : 김나윤 과제 제출

- 김진우/11주차/11-1.py
3행:input 데이터로 1행으로 이루어진 [3,5]를 입력한다.
5행:입력층에서 은닉층 1행 1열의 가중치 행렬이 [2,3]인 것을 뜻한다
6행:입력층에서 은닉층 1행 2열의 가중치 행렬이 [4,-5]인 것을 뜻한다.
7행:은닉층에서 결과층의 가중치 행렬이 [2,7]인 것을 뜻한다.
9행:[3,5]에 2행 1열 크기의 [2,3]을 곱하여 은닉층 1행 1열은 [6+15]이므로 [21]이된다.
10행:[3,5]에 2행 1열 크기의 [4,-5]를 곱하여 은닉층 1행 2열은 [12-25]이므로 [-13]이된다.
11행:가중치를 적용한 값 각각 출력한다.
13행:다시 [21, -13]에 2행 1열의 [2,7]을 곱하여 더해준다.
14행:결과값은 [42-91]이므로 [-49]가 된다
> Week 11 : 김진우 과제 제출

- 김정우/11/11-1.py
import numpy as np
input_data = np.array([3,5])      #입력값 [3,5]생성
weight_hidden_0 = np.array([2,3])      #입력값에 대한 가중치 [2.3]생성
weight_hidden_1 = np.array([4,-5])      #입력값에 대한 두번째 가중치 [4,-5]생성
weight_output = np.array([2,7])      #weight_hidden_0에대한 가중치 2와 weight_hidden_1에대한 가중치 7 [2,7]생성
hidden_0_value = (input_data * weight_hidden_0).sum()       #입력값에 가중치를 곱한 값 3*2+5*3=21
hidden_1_value = (input_data * weight_hidden_1).sum()      #입력값에 두번째 가중치를 곱한 값 3*4+5*(-5)=-13
print(hidden_0_value,hidden_1_value,sep=',')      #21,-13 출력
output = hidden_0_value * weight_output[0] + hidden_1_value * weight_output[1]      #21*2+(-13)*7=-49 의 결과인 -49를 output에 넣음
print(output)      #-49 출력
> Week11 : 김정우 과제 제출

- 구가현/11주차/11.py
import numpy as np
input_data=np.array([3,5]) #바꿈x
weight_hidden_0=np.array([2,3]) #입력값 가중치
weight_hidden_1=np.array([4,-5]) #입력값 가중치2
weight_output=np.array([2,7]) #weight_hidden 가중치
hidden_0_value=(input_data*weight_hidden_0).sum() #계산
hidden_1_value=(input_data*weight_hidden_1).sum() #계산2
print(hidden_0_value,hidden_1_value,sep=',') #결과값
output=hidden_0_value*weight_output[0]+hidden_1_value*weight_output[1] #value값과 가중치값 곱하고 나누기
print(output) #결과값
> Week11 : 구가현 과제 제출

- 조항준/12주차/12-1.py
안녕하세요 12주차 과제 제출합니다. 감사합니다
input_data = 5
weight = 3
target = 8
learning_rate = 0.1
pred = weight * input_data                     #예측값 = 가중치 * 입력값
error = pred - target                           #오차 = 예측값 - 실제값
print("original error:", error)                    
slope = 2 * input_data * error                #오차함수의 기울기 = 2 * 입력값 * 오차
print("slope:",slope)                       
new_weight = weight - learning_rate * slope      #새로운 가중치 = 가중치 - 러닝레이트 * 오차함수 기울기
print("new weight:", new_weight)                   
new_pred = new_weight * input_data                   #새로운 예측값 = 새로운 가중치 * input_data
print("new prediciton:", new_pred)                 
new_error = new_pred - target                            #새로운 오차 = 새로운 예측값 - 실제값
print("new error:", new_error)
#original error : 오차 (7)
#slope : …
> Week 12 : 조항준 과제 제출

- 남지선/12주차/12-1.py
해결되지 않는 문제나 오류, 과제에 대해 궁금한 점은 없습니다!
>  Week 12 : 남지선 과제 제출

- 정원준/12주차/12-1.py
> Week 12 : 정원준 과제 제출

- 김지성/12주차/12.py
입력 값: 5
가중치: 3
목표값: 8
학습률: 0.1
예측값 = 가중치 * 입력 값
오차 = 예측값 - 목표값
오차함수의 기울기 = 2 * 입력값 * 오차
새로운 가중치 = 가중치 - 학습률 * 기울기
새로운 예측값 = 새로운 가중치 * 입력값
새로운 오차 = 새로운 예측값 - 목표값
--> 
오차: 7
기울기: 70
새로운 가중치: -4.0
새로운 예측값: -20.0
새로운 오차: -28.0  출
> Week 12: 김지성 과제 제출

- 김용빈/12주차/12-1.py
입력 값: 5 (input_data)
가중치: 3 (weight)
목표값(실제값): 8 (target)
학습률: 0.1 (learning_rate)
예측값(pred) = 가중치 * 입력 값(초기값)
오차(error) = 예측값 - 목표값(실제값)
오차함수의 기울기(slope) = 2 * 입력값 * 오차
새로운 가중치(new_weight) = 가중치 - 학습률 * 기울기
새로운 예측값(new_pred) = 새로운 가중치 * 입력값
새로운 오차(new_error) = 새로운 예측값 - 목표값
---------------출력값---------------
오차: 7
기울기: 70
새로운 가중치: -4.0
새로운 예측값: -20.0
새로운 오차: -28.0
결과적으로 이러한 값들을 출력합니다.
> Week 12 : 김용빈 과제 제출

- 구가현/12주/12.py
> Week 12 : 구가현 과제 제출

- 한지환/12주차/12-1.py
1~4번 라인: 변수 설정
6번 라인: 예측값 계산
8번 라인: 오차 계산
11번 라인: 오차함수의 기울기 계산
14번 라인: 기울기를 사용해 가중치 업데이
17번 라인: 새로운 예측값 계산
20번 라인: 새로운 오차 계산
> Week12:한지환 과제 제출

- 김정우/12/12-1.py
input_data = 5  #입력값 
weight = 3  #가중치
target = 8  #목표
learning_rate = 0.1 #학습값
pred = weight * input_data #예측값
error = pred - target #오차 = 예측값 - 목표
print("original error : ", error)  #오차 출력
slope = 2 * input_data * error #기울기 = 2 * 입력값 * 오차
print("slope : ", slope)  #오차함수의 기울기 출력
new_weight = weight - learning_rate * slope #새로운 가중치 = 가중치 - 학습값 * 기울기
print("new weight : ", new_weight) #새로운 가중치 출력
new_pred = new_weight * input_data #새로운 예측값 = 새로운 가중치 * 입력값
print("new pred : ", new_pred)#새로운 예측값 출력
new_error = new_pred - target #새로운 오차 = 새로운 예측값 - 목표
print("new error : ", new_error) #새로운 오차 출력
> Week 12 : 김정우 과제 제출

- 최인규/12주차/week12-1.py
이 코드는 입력 데이터와 목표값을 사용하여 가중치를 업데이트하고, 새로운 예측값과 오차를 계산하는 과정으로 이루어져 있으며, 경사 하강법을 사용하여 최적의 가중치(기울기 0)를 찾는 것이 목표입니다. 추가적인 코드에 대한 설명은 각 행에 주석으로 달았습니다.
> Week 12 : 최인규 과제 제출

- 문준호/12주차/12-1.py
초기 예측값을 가중치의 곲과 bias의 합의 형태, 선형으로 구합니다.
이때 발생한 오차를 이용해서 가중치를 개선시켜줘야합니다.
이때 사용하는 것이,  mse를 w로 편미분한 값입니다.
이렇게 되면 2*input_data*(pred - target) 값입니다.
이를 새로운 가중치에 바로 적용시키는 것이 아니라, learning_rate를 이용해서, w를 수정합니다.
> Week 12 : 문준호 과제 제출

- 12-1.py
input_data=5 #입력 받는 값
weight=3 #가중치
target=8 #목표하는 값
learning_rate=0.1 #학습 빈도, 가중치 조절
pred=weight*input_data #가중치*입력 받는 값=예측값
error=pred-target #예측값-목표하는 값=오차
print("original error:", error)
slope=2*input_data*error #2*입력 받는 값*오차=오차함수의 기울기
print("slope:",slope)
new_weight=weight-learning_rate*slope #가중치-학습 빈도*기울기=새로운 가중치
print("new weight:",new_weight)
new_pred=new_weight*input_data #새로운 가중치*입력 받는 값=새로운 예측값
print("new prediction:", new_pred)
new_error=new_pred-target #새로운 예측값-목표 하는 값=새로운 오차
print("new error:", new_error)
리뷰가 인코딩문제로 깨져 보여서 description에 다시 작성하여 제출합니다.
> week 12 : 김세현 과제 제출

- 컴공김태현/12주차/12-1
> Week12: 컴공김태현 과제 제출

- 정원준/13주차/13-1.py
- 정원준/13주차/week13_contents.py
> Week 13 : 정원준 과제 제출

- 조항준/13주차/13-1.py
> Week 13 : 조항준 과제 제출

- 이보윤/12주차/12week.py
- 이보윤/13주차/week13.py
input_data = 3 //값설정
weight = 2
target = 10
learning_rate = 0.01
pred = weight * input_data
error = pred - target
print("original error:", error)  //원래 오류 출력
slope = 2 * input_data * error
print("slope:", slope)  # 기울기 출력
new_weight = weight - learning_rate * slope
print("new_weight:", new_weight)  // 가중치 출력
new_pred = new_weight * input_data
print("new prediction:", new_pred)  #  예측 값 출력
new_error = new_pred - target
print("new error:", new_error)  #  오류 출력
> week 11: 이보윤 과제제출

- 컴공김태현/13주차/diabetes.py
> Week13:컴공김태현 과제 제출

- 남지선/13주차/13-1.py
> Week 13: 남지선 과제제출
